# GREATUHC CONFIG


# These times are in TICKS
# Time before game starts (default 900t/45s)
pre_game_time: 900
# Time for grace period (default 18000t/15m)
grace_period_time: 18000
# Time for PVP (default 30000t/25m)
pvp_time: 30000
# Time for deathmatch (default 18000t/15m)
deathmatch_time: 18000


# Decreases time before deathmatch if few players are left
game_shortener:
  # How many players need to be left to trigger
  players_left: 4
  # Decrease timer to this value if above (in ticks)
  decrease_to: 6000
  # Message to send
  message: "&c&lOnly 4 players left! Timer to deathmatch has been reduced to 5 minutes!"


# 99% of the time your world names should be the defaults
# If your worlds are renamed, change them here
overworld_name: "world"
nether_name: "world_nether"


# Starting main border sizes for overworld/nether/deathmatch
# Note that this is the total size, not the radius, e.g., 1600.0 means -800 to +800
overworld_main_border_start: 1600.0
nether_main_border_start: 400.0
deathmatch_border_start: 140.0
# Ending border sizes for overworld/nether/deathmatch
overworld_main_border_end: 400.0
nether_main_border_end: 100.0
deathmatch_border_end: 20.0
# Time to shrink for the main border
# This is in SECONDS, not TICKS!
main_border_shrink_time: 1500
# The deathmatch border shrinks after :deathmatch_border_shrink_after: TICKS
# And then takes :deathmatch_border_shrink_time: SECONDS after that to fully shrink
# Default: start shrinking 1200t/1m after deathmatch, taking 600s/10m to fully shrink
deathmatch_border_shrink_after: 1200
deathmatch_border_shrink_time: 600


# Deathmatch world generation config
# Simple noise generation is used to build the deathmatch terrain
# Feel free to play around with these values
deathmatch_gen:
  # Blocks will be generated between -r and r (int)
  radius: 90
  # X and Z are both divided by this value before calculating the noise (double)
  xz_noise_scale: 35.0
  # Past this point the terrain begins to grow taller (int)
  # Recommended to put this at/near the starting border
  extra_distance_threshold: 70
  # Block selection noise scale (see xz_noise_scale) (double)
  block_selection_noise_scale: 30.0
  # Chance of each block in the pyramid to be a diamond (double)
  diamond_chance: 0.013
  # Starting y-level of deathmatch terrain generation (int)
  deathmatch_world_height: 307
  # Height of the pyramid (int)
  # Note: :deathmatch_world_height: + :pyramid_height: <= max world height (319)
  pyramid_height: 12
  # Maximum height of deathmatch terrain (int)
  # This is the amount of height variation in the terrain (this is added to :deathmatch_world_height:)
  terrain_height: 5
  # The value <:extra_a: * d**1.4 + :extra_b: * d>, where d from 0 to 1 represents how close we are to the edge
  # of the map (:extra_distance_threshold: to :radius:), is added to the noise value.
  # The defaults were chosen to prevent bedrock from showing on the sides (from ascending too fast) and/or at the
  # top (from going too high)
  # (double)
  extra_a: 0.77
  extra_b: 0.63


# Minimum & maximum spread distance (radius) for players at the beginning of the game
# (These are plugged into the vanilla /spreadplayers command)
main_spread_min: 150
main_spread_max: 650
# All players are spread out EXACTLY this distance from the center
deathmatch_spread_radius: 64.0


# If a player takes environmental (not from a projectile or mob) damage during the grace period, then all other players
# within 1.5 blocks XZ and 3 blocks Y of the player will take the same damage
# This discourages traps where the victim can't get out because the other player is in their face
grace_period_extra_protection: true


# You should probably have this enabled
winner_check: true
