name: GreatUHC
version: '${project.version}'
main: io.github.greatericontop.greatuhc.GreatUHCMain
api-version: 1.18
authors: [greateric]

softdepend: [PlaceholderAPI]

commands:
    uhc:
        description: 'GreatUHC command'
        usage: '§cusage: /uhc'
        aliases: [greatuhc]
    uhcrecipes:
        description: 'GreatUHC unlock recipes command'
        usage: '§cusage: /uhcrecipes'
        aliases: [custom-recipes]