name: GreatUHC
version: '${project.version}'
main: io.github.greatericontop.greatuhc.GreatUHCMain
api-version: 1.18
authors: [greateric]

commands:
    uhc:
        description: 'GreatUHC command'
        usage: '§cusage: /uhc'
        aliases: [greatuhc]