name: GreatUHC
version: '${project.version}'
main: io.github.greatericontop.greatuhc.GreatUHCMain
api-version: 1.18
authors: [greateric]

softdepend: [PlaceholderAPI]

commands:
    greatuhc:
        description: 'GreatUHC command'
        usage: '§cusage: /greatuhc'
        aliases: [uhc]
    uhcrecipes:
        description: 'GreatUHC unlock recipes command'
        usage: '§cusage: /uhcrecipes'
        aliases: [custom-recipes]
    uhcstart:
        description: 'GreatUHC start command'
        usage: '§cusage: /uhcstart'